project_id = "qimelntuxquptqqynxzv"

[functions.sitemap-proxy]
verify_jwt = false

[functions.start-youtube-reprocessing]
verify_jwt = false

[functions.bulk-reprocess-youtube]
verify_jwt = false

[functions.reprocess-youtube-video]
verify_jwt = false

[functions.youtube-metadata]
verify_jwt = false

[functions.test-youtube-integration]
verify_jwt = false

[functions.scrape-og]
verify_jwt = false

[functions.ingest-queue]
verify_jwt = false

[functions.fetch-rss]
verify_jwt = false

[functions.tag-drops]
verify_jwt = false

[functions.tag-drops-test]
verify_jwt = false

[functions.background-feed-ranking]
verify_jwt = false

[functions.restart-ingestion]
verify_jwt = false

[functions.admin-api]
verify_jwt = true

[functions.retag-existing-content]
verify_jwt = true

[functions.admin-retag-drop]
verify_jwt = true

[functions.admin-update-tags]
verify_jwt = true

[functions.admin-delete-drop]
verify_jwt = true

[functions.admin-update-tagging-params]
verify_jwt = true

[functions.retag-all-drops]
verify_jwt = true

[functions.serve-sitemap]
verify_jwt = false

[functions.serve-core-sitemap]
verify_jwt = false

[functions.serve-topics-sitemap]
verify_jwt = false

[functions.serve-topics-archive-sitemap]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false