project_id = "qimelntuxquptqqynxzv"

[functions.scrape-og]
verify_jwt = false

[functions.ingest-queue]
verify_jwt = false

[functions.fetch-rss]
verify_jwt = false

[functions.tag-drops]
verify_jwt = false

[functions.tag-drops-test]
verify_jwt = false

[functions.background-feed-ranking]
verify_jwt = false

[functions.restart-ingestion]
verify_jwt = false

[functions.admin-api]
verify_jwt = true

[functions.retag-existing-content]
verify_jwt = true

[functions.admin-retag-drop]
verify_jwt = true

[functions.admin-update-tags]
verify_jwt = true

[functions.admin-delete-drop]
verify_jwt = true

[functions.admin-update-tagging-params]
verify_jwt = true