project_id = "qimelntuxquptqqynxzv"

[functions.test-embedding-init]
verify_jwt = false

[functions.automated-embeddings]
verify_jwt = false

[functions.sitemap-proxy]
verify_jwt = false

[functions.start-youtube-reprocessing]
verify_jwt = false

[functions.bulk-reprocess-youtube]
verify_jwt = false

[functions.reprocess-youtube-video]
verify_jwt = false

[functions.youtube-metadata]
verify_jwt = false

[functions.test-youtube-integration]
verify_jwt = false

[functions.scrape-og]
verify_jwt = false

[functions.ingest-queue]
verify_jwt = false

[functions.fetch-rss]
verify_jwt = false

[functions.tag-drops]
verify_jwt = false

[functions.tag-drops-test]
verify_jwt = false

[functions.background-feed-ranking]
verify_jwt = false

[functions.restart-ingestion]
verify_jwt = false

[functions.admin-api]
verify_jwt = true

[functions.retag-existing-content]
verify_jwt = true

[functions.admin-retag-drop]
verify_jwt = true

[functions.admin-update-tags]
verify_jwt = true

[functions.admin-delete-drop]
verify_jwt = true

[functions.admin-update-tagging-params]
verify_jwt = true

[functions.retag-all-drops]
verify_jwt = true

[functions.serve-sitemap]
verify_jwt = false

[functions.serve-core-sitemap]
verify_jwt = false

[functions.serve-topics-sitemap]
verify_jwt = false

[functions.serve-topics-archive-sitemap]
verify_jwt = false

[functions.cleanup-failed-queue]
verify_jwt = false

[functions.validate-queue-urls]
verify_jwt = false

[functions.manual-health-fix]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.indexnow-integration]
verify_jwt = false

[functions.test-sitemap-submissions]
verify_jwt = false

[functions.embed-drops]
verify_jwt = false

[functions.send-newsletters]
verify_jwt = false

[functions.send-welcome-newsletter]
verify_jwt = true

[functions.build-digest]
verify_jwt = false

[functions.send-email-digest]
verify_jwt = false

[functions.admin-hard-delete-user]
verify_jwt = true

[functions.send-onboarding-reminders]
verify_jwt = false

[functions.rss-feed]
verify_jwt = false

[functions.unsubscribe-newsletter]
verify_jwt = false

[functions.source-health-monitor]
verify_jwt = true

[functions.youtube-auto-comment]
verify_jwt = false

[functions.youtube-job-creator]
verify_jwt = false

[functions.youtube-refresh-token]
verify_jwt = false