project_id = "qimelntuxquptqqynxzv"

[functions.scrape-og]
verify_jwt = false

[functions.ingest-queue]
verify_jwt = false

[functions.fetch-rss]
verify_jwt = false

[functions.admin-api]
verify_jwt = true