project_id = "qimelntuxquptqqynxzv"

[functions.scrape-og]
verify_jwt = false

[functions.ingest-queue]
verify_jwt = false

[functions.fetch-rss]
verify_jwt = false

[functions.tag-drops]
verify_jwt = false

[functions.tag-drops-test]
verify_jwt = false

[functions.background-feed-ranking]
verify_jwt = false

[functions.admin-api]
verify_jwt = true