-- Create table to log automated ingestion cycles
CREATE TABLE IF NOT EXISTS public.ingestion_logs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  cycle_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
  feeds_processed INTEGER NOT NULL DEFAULT 0,
  new_articles INTEGER NOT NULL DEFAULT 0,
  ingestion_processed INTEGER NOT NULL DEFAULT 0,
  articles_tagged INTEGER NOT NULL DEFAULT 0,
  errors TEXT[] NOT NULL DEFAULT '{}',
  success BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.ingestion_logs ENABLE ROW LEVEL SECURITY;

-- Create policy for admin access
CREATE POLICY "ingestion_logs_admin_access" 
ON public.ingestion_logs 
FOR ALL 
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE id = auth.uid() 
    AND role IN ('admin', 'superadmin')
  )
);

-- Add index for performance
CREATE INDEX IF NOT EXISTS idx_ingestion_logs_timestamp 
ON public.ingestion_logs (cycle_timestamp DESC);